import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import AuthProvider from "./auth/provider";

const inter = Inter({ weight: "400", subsets: ["latin"], display: "swap" });

const noto = Noto_Sans_KR({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${noto.className} bg-white text-black max-w-sm mx-auto`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
